experiment_name: 'frontal_extlosscapimg_globalloss'
phase: 'pretrain'

lightning:
    trainer:
       gpus: '0'
       max_epochs: 50
       distributed_backend: 'dp'
       gradient_clip_val: 0.25
       lr: 0.00005
       precision: 16
    checkpoint_callback:
        monitor: 'r_sum'
        dirpath: './data/ckpt'
        save_last: true 
        mode: max
        save_top_k: 10
    early_stopping_callback:
        monitor: 'r_sum'
        min_delta: 0.00
        patience: 5
        verbose: False
        mode: 'max'
    logger:
        logger_type: 'WandbLogger'
        save_dir: './data/'
        project: 'limitr'

model:
    norm: false
    limitr:
        local_ext_loss_weight: 1.0
        local_int_loss_weight: 0
        global_loss_weight: 1.0
        temp1: 4.0
        temp2: 5.0
        temp3: 10.0
        lateral: False
        pe: False
        img_attn: True
        cap_attn: True
        int_w_method: 'SAF'
    vision:
        model_name: 'resnet_50'
        freeze_cnn: false
        pretrained: true
    text:  
        bert_type: "emilyalsentzer/Bio_ClinicalBERT"
        last_n_layers: 4
        aggregate_method: 'sum'
        norm: false
        embedding_dim: 768
        freeze_bert: false
        agg_tokens: true

data: 
    dataset: mimic
    text: 
      word_num: 97
    image:
        imsize: 256
    data_type: mimic

transforms: 
    norm: 'half'
    random_crop:
        crop_size: 224

train: 
    update_interval: 1000
    batch_size: 48
    num_workers: 18
    optimizer: 
        name: 'Adam'
        weight_decay: 1e-6
    scheduler: 
        name: 'plateau'
        monitor: 'r_sum'
        interval: 'epoch'
        frequency: 1
